name = "curated-mods"
author = "nths"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "793f069e6d6a1857460cfb56ed74e51863bc79b6f3568c4a114837ff82dc5f16"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
