name = "curated-mods"
author = "nths"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5274daf76842696443efb95dd3eadea8982c093afe82d20e243781eee1e5ccb2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
