name = "curated-mods"
author = "nths"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d1a7c64ce2e4c3e9939b3314a3de05a060cbca4db4c87c60e596f61b8449ae3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
